const syllabusResources = {
  1:{title:'Number System & Percentage',subtopics:['Number System: Divisibility Rule','Finding Unit Digit','Greatest & Smallest Fractions','Remainder Theorem','LCM & HCF','Percentage: Basic Percentage','Income-based Problems','Population Model','Election-based Problems','Price & Consumption Model'],formulas:['Percentage = (Part / Whole) × 100','New value after increase = Original × (1 + r/100)','New value after decrease = Original × (1 − r/100)','For successive percentage changes a% and b%: net change = a + b + ab/100 (use signs for increase/decrease)','HCF × LCM = product of two positive integers'],example:'If a price increases from ₹500 by 20%, new price = ₹500 × 1.20 = ₹600.',practice:'Revise divisibility tests, unit digits, remainders and percentage-change models before attempting the 30-question Day 1 test.'},
  2:{title:'Profit & Loss, Ratio & Proportion, Discounts',subtopics:['Profit & Loss: Finding CP, SP, Profit and Loss','Profit % and Loss %','Successive Profit and Loss','Same CP and Same SP','Error Weightage','Discount: SP, MP, Discount and Discount %','Successive Discount','Marked Price and Profit Relation','Ratio: Basic Ratio and Types','Finding Unknown Ratio','Proportion Types'],formulas:['Profit = SP − CP','Loss = CP − SP','Profit% = (Profit/CP) × 100','Loss% = (Loss/CP) × 100','Discount = MP − SP','Discount% = (Discount/MP) × 100','a:b = c:d means ad = bc'],example:'If CP = ₹800 and SP = ₹920, profit = ₹120 and profit% = 15%.',practice:'Practice CP/SP conversions, successive discounts and ratio equations. Then take the Day 2 test.'},
  3:{title:'Partnership & Interest',subtopics:['Partnership: Profit Ratio at Equal Time','Profit Ratio at Different Time','Partner Joins/Leaves at Middle of Time','Investment Added/Withdrawn at Middle of Time','Working and Sleeping Partner','Simple Interest: Principal, Time and Rate','Principal Doubles and Triples','Compound Interest: Half-yearly, Quarterly and Monthly','Difference Between SI and CI','Principal Doubles and Triples'],formulas:['Partnership profit share ∝ Investment × Time','SI = PRT/100','Amount under SI = P + SI','CI amount = P(1 + r/100)^n','Half-yearly: use r/2 and 2n periods','Quarterly: use r/4 and 4n periods'],example:'A invests ₹10,000 for 12 months and B ₹15,000 for 8 months. Both have equal capital-time products, so their profit shares are equal.',practice:'Solve investment-time partnership cases and compare SI with CI for 1–3 periods. Then take Day 3.'},
  4:{title:'Time & Work, Pipes & Cisterns',subtopics:['Time & Work: Combined Work','Before Completion of Work','One Leaves or One Joins','Alternative Work','Pipes & Cisterns: Basic Concept','One Filling and One Emptying Pipe','Two or Three Pipes Filling Together','Alternate Working','Pipe Opened for Some Time and Then Closed'],formulas:['If a person completes work in x days, one-day work = 1/x','Combined rate = sum of individual filling rates','Emptying pipe is treated as negative rate','Time = Total work / combined rate'],example:'A completes a job in 10 days and B in 15 days. Together their rate is 1/10 + 1/15 = 1/6, so they finish in 6 days.',practice:'Use LCM/rate methods, including join/leave and fill/empty cases. Finish Day 4 test after timed practice.'},
  5:{title:'Time & Distance, Trains, Boats & Streams',subtopics:['Time & Distance: Basic Formula Model','Finding Time, Distance and Speed','Constant Distance/Time/Speed','Average Speed','Relative Speed','Problems on Trains: Finding Distance','Tunnel/Bridge/Platform Length','Train Length on Pole/Post Office Model','Relative Speeds','Boats & Streams: Stream Speed','Boat Speed','Finding Distance and Time','Upstream and Downstream Speed'],formulas:['Speed = Distance/Time','Distance = Speed × Time','Time = Distance/Speed','Average speed = Total distance / Total time','Relative speed: add for opposite directions, subtract for same direction','Downstream speed = boat speed + stream speed','Upstream speed = boat speed − stream speed'],example:'A 120 m train crosses a pole in 6 s. Its speed is 120/6 = 20 m/s = 72 km/h.',practice:'Convert km/h and m/s carefully. Practice train-length and upstream/downstream questions before Day 5.'},
  6:{title:'Averages, Ages, Mixtures & Allegations',subtopics:['Averages: Basic Average','Finding Missing Number','Combined/Group Average','Age Added or Removed','Consecutive Numbers Average','Ages: Past and Future Age','Ratio-based Problems','Age Difference','Sum and Product of Ages','Average Age Problems','Family & Multi-person Puzzles','Mixtures & Allegations: Finding Mixture Ratio','Quantity Removal Model','Allegation Rule and Problems','Profit/Loss in Mixtures'],formulas:['Average = Sum of observations / Number of observations','Missing value = Required total − known total','Weighted average = Σ(value × quantity) / Σquantity','Alligation ratio = (Higher − Mean):(Mean − Lower)','After n years, add n to every current age; n years ago, subtract n'],example:'The average of 5 numbers is 18, so their total is 90. If four total 70, the missing number is 20.',practice:'Translate age statements into equations and use alligation for two-value mixtures. Then take the Day 6 test.'},
  7:{title:'Mensuration & Probability',subtopics:['Mensuration: Surface & Areas','Areas & Volumes','Probability: Basic Probability','Types of Events','Addition and Multiplication Rules','Conditional Probability'],formulas:['Rectangle area = l×b; perimeter = 2(l+b)','Triangle area = 1/2×base×height','Circle area = πr²; circumference = 2πr','Cuboid volume = lbh','Probability P(E)=favourable outcomes/total outcomes','For mutually exclusive events: P(A∪B)=P(A)+P(B)','For independent events: P(A∩B)=P(A)P(B)','Conditional probability P(A|B)=P(A∩B)/P(B)'],example:'For one fair die, P(even) = 3/6 = 1/2 because outcomes 2, 4 and 6 are favourable.',practice:'Build a formula sheet for common 2D/3D shapes and solve basic event-probability questions before Day 7.'},
  8:{title:'Permutations & Combinations, Data Interpretation',subtopics:['Fundamental Counting Principle','Permutation','Combination','Circular Permutation','Repetition & Restrictions','Data Interpretation: Tabular Charts','Bar Graphs','Pie Charts','Line Charts'],formulas:['If choices occur in stages, multiply the number of choices','nPr = n!/(n−r)!','nCr = n!/[r!(n−r)!]','nCr = nC(n−r)','Circular arrangements of n distinct objects = (n−1)!','Percentage from pie chart = angle/360 × 100'],example:'The number of ways to arrange 3 different books is 3! = 6.',practice:'Decide whether order matters before choosing permutation or combination. For DI, read totals and units before calculating.'},
  9:{title:'Series, Coding-Decoding, Analogy & Directions',subtopics:['Series: Number Series','Letter Series','Alphabetical Series','Wrong Number','Coding & Decoding: Letter Coding','Number Coding','Letter and Number Coding','Chinese Code','Word Substitution Code','Directions: Direct Type','Shadow Model','Clockwise and Anti-clockwise','Analogy: Number Analogy','Letter Analogy','Word Analogy'],formulas:['Check common differences, ratios and alternating patterns in number series','Map A=1,…,Z=26 when alphabet positions are useful','For directions, fix North first and track each turn','Clockwise: N→E→S→W; anti-clockwise: N→W→S→E'],example:'For 2, 5, 10, 17, 26, differences are 3, 5, 7, 9, so the next term is 37.',practice:'Use a systematic pattern checklist for series/codes and draw a quick compass for direction questions. Then take Day 9.'},
  10:{title:'Ranking, Syllogisms & Seating Arrangement',subtopics:['Ranking: From Left or Right','From Top or Bottom','Syllogisms: Exactly Conditions','Possibility Conditions','Seating Arrangement: Linear Arrangement','Circular Arrangement','Statements: Assumptions','Conclusions'],formulas:['Total persons = left rank + right rank − 1','Rank from opposite end = total − given rank + 1','For syllogisms, translate statements into set relationships and test conclusions','For linear seating, fix a reference position before placing constraints','For circular seating, fix one person to remove rotational duplicates'],example:'If a student is 15th from the left and 10th from the right, total students = 15 + 10 − 1 = 24.',practice:'Draw diagrams for syllogisms and seating constraints instead of solving only mentally. Finish with the Day 10 assessment.'}
};

function injectResourceStyles(){
  if(document.getElementById('resourceStyles')) return;
  const style=document.createElement('style'); style.id='resourceStyles';
  style.textContent=`.resource-panel{margin-top:14px;padding:14px;border:1px solid #eceef4;border-radius:12px;background:#fbfbfe}.resource-panel h4{margin:0 0 9px;font:700 10px 'Space Grotesk';color:#30384b}.resource-panel ul{margin:0;padding-left:17px;color:#727b8d;font-size:9px;line-height:1.85}.resource-formulas{display:grid;gap:6px;margin-top:9px}.formula{padding:7px 9px;border-radius:8px;background:#fff;border:1px solid #eef0f5;color:#596274;font-size:9px}.resource-example{margin-top:10px;padding:9px;border-left:3px solid #7568f0;background:#f7f6ff;color:#60697b;font-size:9px;line-height:1.55}.resource-example b{display:block;color:#4e43c9;margin-bottom:3px}.resource-footer{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-top:12px}.resource-label{font-size:8px;color:#8e96a7}.resource-test-link{font:700 9px 'DM Sans';color:#5b4ce6;text-decoration:none;background:#efedff;padding:7px 9px;border-radius:7px}.resource-test-link:hover{background:#e5e1ff}`;
  document.head.appendChild(style);
}

function renderSyllabusResources(){
  injectResourceStyles();
  document.querySelectorAll('.daily-test-card').forEach(card=>{
    const dayText=card.querySelector('.day-number')?.textContent||'';
    const match=dayText.match(/DAY\s+(\d+)/i); if(!match)return;
    const day=Number(match[1]), r=syllabusResources[day]; if(!r || card.querySelector('.resource-panel'))return;
    const topics=r.subtopics.map(x=>`<li>${x}</li>`).join('');
    const formulas=r.formulas.map(x=>`<div class="formula">${x}</div>`).join('');
    const example=`<div class="resource-example"><b>Worked example</b>${r.example}</div>`;
    const practice=`<div class="resource-footer"><span class="resource-label">Revision guide · ${r.subtopics.length} syllabus points</span><a class="resource-test-link" href="${card.querySelector('.start-test')?.dataset.testUrl||'#'}" target="_blank" rel="noopener">Practice Day ${day} Test ↗</a></div>`;
    const panel=document.createElement('div'); panel.className='resource-panel';
    panel.innerHTML=`<h4>Study Resources</h4><ul>${topics}</ul><h4 style="margin-top:12px">Formula & Concept Sheet</h4><div class="resource-formulas">${formulas}</div>${example}${practice}`;
    const info=card.querySelector('.daily-info'); info ? info.insertAdjacentElement('afterend',panel) : card.appendChild(panel);
  });
}

function bootResources(){
  renderSyllabusResources();
  const observer=new MutationObserver(()=>renderSyllabusResources());
  const target=document.querySelector('.content'); if(target)observer.observe(target,{childList:true,subtree:true});
}

if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',bootResources); else bootResources();
